package com.lee.collection.mapper;

import com.lee.collection.entities.AddressBak;

public interface AddressBakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(AddressBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(AddressBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    AddressBak selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(AddressBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AddressBak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_bak
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(AddressBak record);
}