package com.lee.collection.mapper;

import com.lee.collection.entities.AddressCopy1;

public interface AddressCopy1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(AddressCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(AddressCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    AddressCopy1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(AddressCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(AddressCopy1 record);
}