package com.lee.collection.mapper;

import com.lee.collection.entities.CaseInfoBakWithBLOBs;

public interface CaseInfoBakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info_bak
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(CaseInfoBakWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info_bak
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(CaseInfoBakWithBLOBs record);
}