package com.lee.collection.mapper;

import java.util.List;
import java.util.Map;

import com.lee.collection.entities.CaseBatch;
import com.lee.collection.entities.ObjectCaseBatch;

public interface CaseBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Tue Apr 24 14:27:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Tue Apr 24 14:27:50 CST 2018
     */
    int insert(CaseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Tue Apr 24 14:27:50 CST 2018
     */
    int insertSelective(CaseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Tue Apr 24 14:27:50 CST 2018
     */
    CaseBatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Tue Apr 24 14:27:50 CST 2018
     */
    int updateByPrimaryKeySelective(CaseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Tue Apr 24 14:27:50 CST 2018
     */
    int updateByPrimaryKey(CaseBatch record);

	List<ObjectCaseBatch> getAll();

	int updateCaseBatchState(Integer id);

	List<ObjectCaseBatch> selectCaseBatch(Map<String, Object> map);
}