package com.lee.collection.mapper;

import com.lee.collection.entities.CasePaid;

public interface CasePaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Tue Apr 24 14:28:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Tue Apr 24 14:28:40 CST 2018
     */
    int insert(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Tue Apr 24 14:28:40 CST 2018
     */
    int insertSelective(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Tue Apr 24 14:28:40 CST 2018
     */
    CasePaid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Tue Apr 24 14:28:40 CST 2018
     */
    int updateByPrimaryKeySelective(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Tue Apr 24 14:28:40 CST 2018
     */
    int updateByPrimaryKey(CasePaid record);
}