package com.lee.collection.mapper;

import com.lee.collection.entities.CaseApply;
import com.lee.collection.entities.CaseApplyWithBLOBs;

public interface CaseApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(CaseApplyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(CaseApplyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    CaseApplyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(CaseApplyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseApplyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(CaseApply record);
}