package com.lee.collection.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lee.collection.entities.CaseInfo;

public interface CaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Tue Apr 24 14:28:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Tue Apr 24 14:28:16 CST 2018
     */
    int insert(CaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Tue Apr 24 14:28:16 CST 2018
     */
    int insertSelective(CaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Tue Apr 24 14:28:16 CST 2018
     */
    CaseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Tue Apr 24 14:28:16 CST 2018
     */
    int updateByPrimaryKeySelective(CaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Tue Apr 24 14:28:16 CST 2018
     */
    int updateByPrimaryKey(CaseInfo record);

	int batchInsert(@Param("listCaseInfo") List<CaseInfo> listCaseInfo);

	List<CaseInfo> getAll();

	List<CaseInfo> selectInfosByBatchCode(String batchCode);
}