package com.lee.collection.mapper;

import com.lee.collection.entities.CaseLinkman;
import com.lee.collection.entities.CaseLinkmanWithBLOBs;

public interface CaseLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    CaseLinkmanWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseLinkmanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(CaseLinkman record);
}