package com.lee.collection.mapper;

import com.lee.collection.entities.CaseApplyCopy;
import com.lee.collection.entities.CaseApplyCopyWithBLOBs;

public interface CaseApplyCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(CaseApplyCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(CaseApplyCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    CaseApplyCopyWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKeySelective(CaseApplyCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseApplyCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKey(CaseApplyCopy record);
}