package com.lee.collection.mapper;

import com.lee.collection.entities.CaseCarLoan;

public interface CaseCarLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(CaseCarLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(CaseCarLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    CaseCarLoan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(CaseCarLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(CaseCarLoan record);
}