package com.lee.collection.mapper;

import com.lee.collection.entities.CccWithBLOBs;

public interface CccMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccc
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(CccWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccc
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(CccWithBLOBs record);
}