package com.lee.collection.mapper;

import com.lee.collection.entities.CnoOutStatistics;

public interface CnoOutStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cno_out_statistics
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cno_out_statistics
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(CnoOutStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cno_out_statistics
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(CnoOutStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cno_out_statistics
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    CnoOutStatistics selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cno_out_statistics
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(CnoOutStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cno_out_statistics
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(CnoOutStatistics record);
}