package com.lee.collection.mapper;

import com.lee.collection.entities.CusCity;

public interface CusCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(Long cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(CusCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(CusCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    CusCity selectByPrimaryKey(Long cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(CusCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(CusCity record);
}