package com.lee.collection.mapper;

import java.util.List;

import com.lee.collection.entities.EmployeeInfo;
import com.lee.collection.entities.ObjectEmployee;

public interface EmployeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Mon Apr 23 23:09:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Mon Apr 23 23:09:01 CST 2018
     */
    int insert(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Mon Apr 23 23:09:01 CST 2018
     */
    int insertSelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Mon Apr 23 23:09:01 CST 2018
     */
    EmployeeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Mon Apr 23 23:09:01 CST 2018
     */
    int updateByPrimaryKeySelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Mon Apr 23 23:09:01 CST 2018
     */
    int updateByPrimaryKey(EmployeeInfo record);

	List<ObjectEmployee> getAll();

	int deleteEmployees(List<EmployeeInfo> list);

	int batchEnablestatus(List<EmployeeInfo> list);

	int batchUnablestatus(List<EmployeeInfo> list);

	List<EmployeeInfo> queryEmployee(EmployeeInfo employee);
}