package com.lee.collection.mapper;

import java.util.List;
import java.util.Map;

import com.lee.collection.entities.Entrust;

public interface EntrustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(Entrust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(Entrust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    Entrust selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKeySelective(Entrust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKey(Entrust record);

	List<Entrust> getAll();

	int batchUpdateState(List<Entrust> list);

	int batchUnableState(List<Entrust> list);

	int deleteByIds(List<Entrust> list);

	List<Entrust> queryEntrust(Map<Object, Object> map);
}