package com.lee.collection.mapper;

import com.lee.collection.entities.HurryRecord;

public interface HurryRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(HurryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(HurryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    HurryRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(HurryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(HurryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hurry_record
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(HurryRecord record);
}