package com.lee.collection.mapper;

import com.lee.collection.entities.MessageReminder;

public interface MessageReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(MessageReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(MessageReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    MessageReminder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKeySelective(MessageReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int updateByPrimaryKey(MessageReminder record);
}