package com.lee.collection.mapper;

import com.lee.collection.entities.Sheet0;

public interface Sheet0Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet0
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(Sheet0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet0
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(Sheet0 record);
}