package com.lee.collection.mapper;

import com.lee.collection.entities.Ss;

public interface SsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(Ss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(Ss record);
}