package com.lee.collection.mapper;

import com.lee.collection.entities.SysColumnCopy;

public interface SysColumnCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(SysColumnCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(SysColumnCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    SysColumnCopy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(SysColumnCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int updateByPrimaryKey(SysColumnCopy record);
}