package com.lee.collection.mapper;

import com.lee.collection.entities.SysRoleResourceRelationKey;

public interface SysRoleResourceRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_relation
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int deleteByPrimaryKey(SysRoleResourceRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_relation
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insert(SysRoleResourceRelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_relation
     *
     * @mbggenerated Sat Apr 21 19:12:59 CST 2018
     */
    int insertSelective(SysRoleResourceRelationKey record);
}