package com.lee.collection.mapper;

import com.lee.collection.entities.Table2;

public interface Table2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insert(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Sat Apr 21 19:12:58 CST 2018
     */
    int insertSelective(Table2 record);
}